@startuml loris.data.manager.DataManager
set namespaceSeparator none
class "DataManager" as loris.data.manager.DataManager {
  components: ComponentContext
  connectors: ConnectorContext
  connect(*connectors: Connector) -> None
  reconnect(*connectors: Connector) -> None
  disconnect(*connectors: Connector) -> None
  read(channels: Optional[Channels], start: Optional[pd.Timestamp], end: Optional[pd.Timestamp]) -> pd.DataFrame
  write(data: pd.DataFrame, channels: Optional[Channels]) -> None
  log(channels: Optional[Channels], force: bool) -> None
}
class "DataContext" as loris.data.context.DataContext {
  channels: Channels
  filter(filter: Callable[[Channel], bool]) -> Channels
  groupby(by: str) -> List[Tuple[Any, Channels]]
  to_frame() -> pd.DataFrame
}
class "ComponentContext" as loris.components.context.ComponentContext {
}
class "ConnectorContext" as loris.connectors.context.ConnectorContext {
}
class "Activator" as loris.core.activator.Activator {
  name: str
  {abstract}activate() -> None
  {abstract}deactivate() -> None
  is_active() -> bool
}
class "Registrator" as loris.core.register.registrator.Registrator {
  TYPE: str
  SECTION: str
  SECTIONS: Collection[str]
  context: RegistratorContext
  id: str
  key: str
}
class "RegistratorContext" as loris.core.register.context.RegistratorContext {
  SECTION
  filter(filter: Callable[[R], bool]) -> Collection[R]
  get_all() -> Collection[R]
  get_first() -> Optional[R]
  get_last() -> Optional[R]
  get_types() -> Collection[str]
  has_type() -> bool
}
class "Configurator" as loris.core.configs.configurator.Configurator {
  context: Context
  configs: Configurations
  {abstract}configure(configs: Configurations) -> None
  is_configured() -> bool
  is_enabled() -> bool
}
class "ThreadPoolExecutor" as concurrent.futures.thread.ThreadPoolExecutor {
  shutdown(wait)
  submit()
}

loris.core.register.registrator.Registrator --|> loris.core.configs.configurator.Configurator
loris.core.register.registrator.Registrator - loris.core.register.context.RegistratorContext : 0..*
loris.core.activator.Activator --|> loris.core.register.registrator.Registrator
loris.data.context.DataContext --|> loris.core.configs.configurator.Configurator
loris.data.manager.DataManager --|> loris.data.context.DataContext
loris.data.manager.DataManager --|> loris.core.activator.Activator
loris.data.manager.DataManager *-- loris.components.context.ComponentContext : _components
loris.data.manager.DataManager *-- loris.connectors.context.ConnectorContext : _connectors
loris.data.manager.DataManager *-- concurrent.futures.thread.ThreadPoolExecutor : _executor
loris.components.context.ComponentContext --|> loris.core.register.context.RegistratorContext
loris.components.context.ComponentContext --|> loris.core.configs.configurator.Configurator
loris.connectors.context.ConnectorContext --|> loris.core.register.context.RegistratorContext
loris.connectors.context.ConnectorContext --|> loris.core.configs.configurator.Configurator
@enduml
