#!/bin/sh
set -e

#DEBHELPER#

case "$1" in
    install)
        # Initiate the virtual environment, if it does not exist
        python=/usr/lib/lori/bin/python
        if [ ! -e $python ]; then
            python3 -m venv /usr/lib/lori
        fi
        $python -m pip install --upgrade pip
        ;;
    *)
        ;;
esac

exit 0
